[package]
name = "color-shredder-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
rstar = { workspace = true }
fastrand = { workspace = true }
serde = { workspace = true, optional = true }
rayon = { workspace = true, optional = true }

[features]
default = ["serde", "rayon"]
serde = ["dep:serde"]
rayon = ["dep:rayon"]
